[deployments]
rpcs = [
"https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://opt-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://arb-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://polygon-amoy.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://gnosis-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://bnb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://bnb-testnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://avax-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://avax-fuji.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://scroll-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://scroll-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://sonic-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://sonic-blaze.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://rpc.fuse.io",
"https://rpc.fusespark.io",
"https://odyssey.ithaca.xyz",
"https://rpc.garnetchain.com",
"https://holesky.drpc.org",
"https://berchain-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://berachain-bartio.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://blast-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://blast-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://worldchain-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://worldchain-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://abstract-testnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://taiko-mainnet.gateway.tenderly.co",
"https://taiko-hekla.gateway.tenderly.co",
"https://build.onbeam.com/rpc",
"https://build.onbeam.com/rpc/testnet",
"https://testnet-rpc.monad.xyz",
"https://network.ambrosus.io",
"https://network.ambrosus-test.io",
"https://json-rpc.evm.iotaledger.net",
"https://json-rpc.evm.testnet.iotaledger.net",
"https://rpc.soneium.org",
"https://rpc.minato.soneium.org",
"https://carrot.megaeth.com/rpc",
"https://rpc.mantle.xyz",
"https://rpc.testnet.mantle.xyz",
"https://ink-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://ink-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://linea-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://linea-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://unichain-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://zora-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
"https://zora-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
]

[deployments.verifier]
# required to enable verification
api_key="${ETHERSCAN_API_KEY}"

[deployments.dependencies]

[deployments.singleton.Safe7579]
file = "./artifacts/Safe7579/Safe7579.json"
source_file="./artifacts/Safe7579/verify.json"
salt = "0x0000000000000000000000000000000000000000d21f121ea506a800a7422403"

[deployments.singleton.Safe7579Launchpad]
file = "./artifacts/Safe7579Launchpad/Safe7579Launchpad.json"
source_file="./artifacts/Safe7579Launchpad/verify.json"
args_sig = "(address,address)"
args = [
"0x0000000071727De22E5E9d8BAf0edAc6f37da032",
"0x000000000069E2a187AEFFb852bF3cCdC95151B2"
]
salt = "0x0000000000000000000000000000000000000000c252bee936886a01c9ae3966"
